### ISSUE TITLE
Additional path elements for specific details?

### ISSUE THREAD

**Issue by ylluminate** [wtfismyip/wtfismyip#11]
Currently `curl https://wtfismyip.com/text` gets the IP address. Could we have some additional functionality where we could get specific fields the geolocation via `curl https://wtfismyip.com/text/geo`,  `curl https://wtfismyip.com/text/city`, or `curl https://wtfismyip.com/text/isp`? Even `curl https://wtfismyip.com/text/ip` would be useful for clarity.

**Comment by wtfismyip** [comment]
We could do that. In the meantime, this will work:

```
$ curl -s https://wtfismyip.com/json | jq .YourFuckingLocation
"Columbus, OH, United States"
```

**Comment by ylluminate** [comment]
Nice, I've been in (many) situations where `jq` isn't (or any such tools are) available or convenient. I'm working at a remote site right now where this is one such case on a system that needs to use this routinely. :)

**Comment by wtfismyip** [comment]
Makes sense, I'll put something together.

**Comment by wtfismyip** [comment]
Took a stab and deployed. Feel free to submit a pull request for improvements: https://github.com/wtfismyip/wtfismyip/commit/cdd69338e4f7c57a3b6b2287d59abfaf51255d77

**Comment by ylluminate** [comment]
That is so nice of  you, thank you! FYI, I see you're using Go, you might want to check out V: https://vlang.io/ (Discord: https://discord.gg/vlang). Most inbound folks are saying it's "Go done right".

**Comment by wtfismyip** [comment]
Hadn't looked into V, will check it out!

**Comment by ylluminate** [comment]
Hey thanks again - this has been super, super helpful. One thing I noticed sometimes is that `curl -s http://wtfismyip.com/text/ip` sometimes emits an additional newline before the IP... I can't figure out what would do this, but I thought I should mention it.

**Comment by ruoho** [comment]
Hey that's pretty weird. I can't reproduce this behavior. Let me know if you figure anything out.
