### ISSUE TITLE
double text handler

### ISSUE THREAD

**Issue by Poolitzer** [wtfismyip/wtfismyip#13]
https://github.com/wtfismyip/wtfismyip/blob/07be4332647cebc657e81c5bccdb013671048e84/wtf/wtf.go#L101
https://github.com/wtfismyip/wtfismyip/blob/07be4332647cebc657e81c5bccdb013671048e84/wtf/wtf.go#L107

I never wrote something in go but if I am not mistaken, this is there twice, which should be unnecessary, since the first text handles it already.

**Comment by wtfismyip** [comment]
Hey @Poolitzer sorry for the super fucking late reply. Fixed in https://github.com/wtfismyip/wtfismyip/commit/f22e7d8a41d26a1b06d2ba78e12c82cf804335e9. Good catch.

**Comment by Poolitzer** [comment]
No worries, glad to help
