### ISSUE TITLE
isp with ampersand looks wrong

### ISSUE THREAD

**Issue by wfleurant** [wtfismyip/wtfismyip#18]
hello,
i cannot tell if the database (GeoIP2-ISP.mmdb) is holding this fucked value `1&amp;`  
or, if `&` is being translated from `geoText{isp.ISP...}`  
so, for ISP with the `&` character it looks wrong as fuck ie  
`"ISP": "1&amp;1 Internet AG",`

**Comment by wtfismyip** [comment]
Fuck. Did that happen on /json or https://json.wtfismyip.com? If so, I'm aware and it's not the Maxmind database. The code is currently escaping /json as HTML using the standard golang template functionality, which is incorrect behavior. I was too lazy to do it correctly, but I'll fix.

**Comment by wfleurant** [comment]
```
🦝 % myip | perl -MHTML::Entities -pe 'decode_entities($_)'
{...
  "ISP": "F&ckin'A Online",
...}
```
