### ISSUE TITLE
IPv6.wtfismyip.com not reachable

### ISSUE THREAD

**Issue by antreos** [wtfismyip/wtfismyip#19]
The IPv6 site doesn't seem to work. 

https://atlas.ripe.net/measurements/30316068/#map

https://atlas.ripe.net/measurements/30316069/#probes

**Comment by wtfismyip** [comment]
Might be an issue with Hetzner, or something is b0rken in Linux 5.12.5.

**Comment by wtfismyip** [comment]
Fixed
