### ISSUE TITLE
Cow says...

### ISSUE THREAD

**Issue by dwarfpuzzles** [wtfismyip/wtfismyip#25]
______________________________________
< Let me fucking have the private key! >
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by wtfismyip** [comment]
```
[ 0 14:39:56 root@jeaux ~/wtfismyip/certs ] # cowsay -t 'Nice try mofo!'
 ________________
< Nice try mofo! >
 ----------------
        \   ^__^
         \  (--)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by dwarfpuzzles** [comment]
Plot twist: The cow was starving for private keys.
