### ISSUE TITLE
Fucking cert won't work when curling in Ubuntu 14.04

### ISSUE THREAD

**Issue by dwarfpuzzles** [wtfismyip/wtfismyip#26]
Here's the fucking message:
funny@ubuntu:~$ curl https://myip.wtf
curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by wtfismyip** [comment]
Probably the previous Let's Encrypt root cross-signing cert expiration. Is https://superuser.com/questions/1679204/curl-on-ubuntu-14-all-lets-encrypt-certificates-are-expired-error-60 helpful at all?

**Comment by dwarfpuzzles** [comment]
Same problem.

**Comment by dwarfpuzzles** [comment]
Theres also this:
Android made a design decision to ignore the expiry on root certificates (it's arguable that expiry on root certificates doesn't make much sense in the first place).

"lets encrypt" is a relatively new CA and to support existing systems their root was "cross-signed"* by DST. The DST root certificate has now expired but because of the aforementioned android behavior a cross signature is still useful for supporting clients running old versions of andriod.

When such a chain is used on a system with a modern root certificate list the cross signature should be ignored and the IRSG (lets encrypt) root should be used. Unfortunately openssl 1.0.x does not handle this scenario correctly.

This issue can be worked around by removing the old DST root certificate. When this is done the chain will correctly be built to the IRSG root.

* My understanding is that technically the "cross signature" consists of an "intermediate certificate" with the same content and key as Lets Encrypt's root certificate.

**Comment by wtfismyip** [comment]
Perhaps it's time to upgrade to Ubuntu 20.04!

**Comment by dwarfpuzzles** [comment]
ubuntu disables updates to skip to ubuntu 20.04 and instead nag you to fucking upgrade to 15.04 if you manage to get into 20.04 your kinda lucky

**Comment by dwarfpuzzles** [comment]
Closed as this is a inactive issue.
