### ISSUE TITLE
Fucking ip isn't in bold and larger font anymore. It sucks me.

### ISSUE THREAD

**Issue by arch-user-france1** [wtfismyip/wtfismyip#27]
PLEASE REVERT

**Comment by wtfismyip** [comment]
That's fucking strange, nothing should be different on the backend.

**Comment by arch-user-france1** [comment]
Well did you ever make the text like IP and all that fucking bold? Or am I just dumb?

**Comment by wtfismyip** [comment]
Here's the HTML template for the fucking frontend:

https://github.com/wtfismyip/wtfismyip/blob/master/wtf/static/static/html.template

I don't think I've touched the inline CSS in the past 10 years, other than the pull request from that awesome motherfucker who implemented dark mode.

**Comment by arch-user-france1** [comment]
That's fucking special
So it isn't bold if I look right.. My brain's mistake.

**Comment by arch-user-france1** [comment]
Can I support wtfismyip without donating?
I've a server at home if it's helpful.
I don't see that I can help by contributing code because the site has what it needs.. Can I do something anyway?

**Comment by wtfismyip** [comment]
Contributing code would be great. If you are good with golang (or want to learn it) I've been meaning to implement https://github.com/wtfismyip/wtfismyip/issues/23 for months now
