### ISSUE TITLE
Tor Exit Status is not correctly reported when connecting via IPv6-capable exit relay

### ISSUE THREAD

**Issue by GGegenhuber** [wtfismyip/wtfismyip#29]
When connecting to the site via the TorBrowser the field `YourFuckingTorExit` is not correctly set when the selected exit relay connects via IPv6 (this is currently the case for about 70% of exit bandwidth/probability).

Example with a randomly selected exit node:
_https://ipv4.wtfismyip.com/json_:
```
{
    "YourFuckingIPAddress": "185.243.218.32",
    "YourFuckingLocation": "Unknown",
    "YourFuckingHostname": "exit-no3.yggdrasil.ws",
    "YourFuckingISP": "TerraHost",
    "YourFuckingTorExit": true,
    "YourFuckingCountryCode": "Unknown"
}
```

_https://ipv6.wtfismyip.com/json_ (and also _https://wtfismyip.com/json_):
```
{
    "YourFuckingIPAddress": "2a03:94e0:ffff:185:243:218:0:32",
    "YourFuckingLocation": "Sandefjord, 38, Norway",
    "YourFuckingHostname": "exit-no3.yggdrasil.ws",
    "YourFuckingISP": "TerraHost",
    "YourFuckingTorExit": false,
    "YourFuckingCountryCode": "NO"
}
```

In the sourcecode, the corresponding lookup is deferred to redis: https://github.com/wtfismyip/wtfismyip/blob/327305ab49370bdc85c9414d052f75b5b7a8f4e6/wtf/wtf.go#L578
I assume it just checks for IPv4 exit addresses. However, Tor already supports IPv6.

**Comment by wtfismyip** [comment]
We're currently pulling those addresses from https://check.torproject.org/torbulkexitlist. Do you happen to know if there is another list that includes IPv6?

**Comment by GGegenhuber** [comment]
I did some further investigation and seemingly this functionality is not fully implemented even at the Tor project itself. For example, I found some outdated issues that discuss the missing IPv6 support of various reporting systems (e.g., https://gitlab.torproject.org/legacy/trac/-/issues/24034 that is referring to the endpoint you're currently using). Additionally, it seems like they just removed the AAAA record for their own Tor-checker to prevent reporting a wrong Tor status when using IPv6 ready exit nodes: https://gitlab.torproject.org/legacy/trac/-/issues/19940

Besides the simplistic `torbulkexitlist` interface, Tor also offers more verbose insights into their current state of relays: https://metrics.torproject.org/onionoo.html

This endpoint provides a full list of all relay nodes and their attributes (in json-format): https://onionoo.torproject.org/details
Although the `exit_addresses` list only contains the first IPv4 address that belongs to the node, the `or_addresses` object has the IPv6 address that is used to connect to a relay (which is usually also the same that is used for exiting IPv6 traffic).

Afaik, the current best approach to get an IPv6 exit list is to iterate over the details list and check for the following conditions:
- whether the relay is online (get maximum value for `last_seen` and filter for all probes that match this number)
- whether the relay is also an exit node (check if `exit_probability` > 0)
- whether the relay supports IPv6 (check the `or_addresses` array for any IPv6 addresses)
This results in a list of all exit nodes that have IPv6 support (currently about 70% of exit bandwidth/probability).

I've found a website that provides alternative Tor exit lists and also follows a similar strategy: https://fissionrelays.net/lists
The corresponding code snippet was also published: https://gitlab.com/fissionrelays/lists/-/blob/master/tor.php

However, besides compiling such a list on own initiative, it might be a good idea to ping the Tor guys asking for a better (and simpler) approach to get IPv6 exit relays. :)

**Comment by wtfismyip** [comment]
Hey! Thanks for noticing this. I had code to store exit node IP addresses using a scheme like you suggested, but lost it in an upgrade. I'll try and hack together something in golang for better identification of Tor exits.

**Comment by wtfismyip** [comment]
Fixed this shit!
