### ISSUE TITLE
Accidental removal of CORS headers?

### ISSUE THREAD

**Issue by haguenau** [wtfismyip/wtfismyip#3]
Hi, and thanks for all the WTF.

Could it be that the recent rewrite in Go lost the CORS header (I assume it used to be `Access-Control-Allow-Origin: *`)? I believe this is needed to allow webpages to access e.g. the `/json` endpoint without running into permission issues.

I hope this is accidental, but, if not, I'm always interested in hearing a good story.

If the header was _meant_ to be there, then I would be happy to provide a patch to reinstate it, if that helps.

**Comment by wtfismyip** [comment]
Yep, I unintentionally forgot to add it in the rewrite. Should be back now.

**Comment by haguenau** [comment]
Indeed, that looks fixed to me!
Thanks for the quick response.
