### ISSUE TITLE
IP 172.19.1.1 with ipv6 enabled

### ISSUE THREAD

**Issue by lucasheld** [wtfismyip/wtfismyip#4]
Hey,
it looks like there is a bug related to ipv6.
The ipv4 mode works as expected but with ipv6 enabled the internal docker ip address 172.19.1.1 is shown.
A few days ago ipv6 was still working.
![4JwMySM](https://user-images.githubusercontent.com/44499529/68509721-e3862200-0271-11ea-8c3b-a76587bc9756.png)

**Comment by wtfismyip** [comment]
Could you try again? OVH has really lousy IPv6 support, and ipv6-nat is a temporary workaround. I've seen this condition before and haven't determined what triggers it.

**Comment by lucasheld** [comment]
Now it's working great. Thank you!

**Comment by SixFive7** [comment]
Hi there, I'm sorry to tell you that it is broken again. Coming from IPv6 I'm getting the IP 172.19.1.1.

**Comment by wtfismyip** [comment]
@SixFive7 Yuck. Should be fixed now. I'll update it with real IPv6 support so I don't have to do the stupid NAT hack.

**Comment by wtfismyip** [comment]
And I'll set up some proper monitoring.

**Comment by SixFive7** [comment]
Many thanks!

**Comment by daguej** [comment]
FYI I'm seeing this again right now

**Comment by wtfismyip** [comment]
Fixed again for the time being, will just get rid of ipv6nat shortly.
